apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: threetierapp
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: cart
  namespace: threetierapp
  labels:
    project: threetierapp
    component: cart
    tier: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      project: threetierapp
      component: cart
      tier: backend

  template:
    metadata:
      labels:
        project: threetierapp
        component: cart
        tier: backend

    spec:
      containers:
      - name: cart
        image: vikasae/cart:v1   # here already 8080 port opens 
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart
        ports:  # just for information
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15

---
apiVersion: v1
kind: Service

metadata:
  name: cart

spec:
  selector:
    project: threetierapp
    component: cart
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080