apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: threetierapp
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalogue
  namespace: threetierapp
  labels:
    project: threetierapp
    component: catalogue
    tier: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      project: threetierapp
      component: catalogue
      tier: backend

  template:
    metadata:
      labels:
        project: threetierapp
        component: catalogue
        tier: backend

    spec:
      containers:
      - name: catalogue
        image: vikasae/catalogue:v1   # here already 8080 port opens 
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: catalogue
        ports:  # just for information
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15

---
apiVersion: v1
kind: Service

metadata:
  name: catalogue

spec:
  selector:
    project: threetierapp
    component: catalogue
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080