apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: threetierapp
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/users"
  REDIS_URL: "redis://redis:6379"

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: user
  namespace: threetierapp
  labels:
    project: threetierapp
    component: user
    tier: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      project: threetierapp
      component: user
      tier: backend

  template:
    metadata:
      labels:
        project: threetierapp
        component: user
        tier: backend

    spec:
      containers:
      - name: user
        image: vikasae/user:v1   # here already 8080 port opens 
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user
        ports:  # just for information
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15

---
apiVersion: v1
kind: Service

metadata:
  name: user

spec:
  selector:
    project: threetierapp
    component: user
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080